name: Daily Commit

on:
  schedule:
    - cron: '11 19 * * *' # Runs daily at 11:19 PM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make a change
        run: |
          echo "$(date)" >> daily_log.txt

      - name: Commit changes
        run: |
          git config user.name "Your Name"
          git config user.email "21f3001019@tds.study.iitm.ac.in"
          git add daily_log.txt
          git commit -m "Daily update by 21f3001019@tds.study.iitm.ac.in"
          git push
