name: Daily Commit

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 5 * * *'  

jobs:
  commit_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 21f3001091@ds.study.iitm.ac.in - Update File
        run: |
          echo "Last run: $(date)" > commit.txt
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "21f3001091@ds.study.iitm.ac.in"
          git add commit.txt
          git commit -m "Automated daily commit - $(date)"
          git push
