name: Daily Automated Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  update-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create logs directory
      run: mkdir -p logs

    - name: Update daily log
      run: echo "Daily update: $(date '+%Y-%m-%d %H:%M:%S UTC')" >> logs/daily-updates.log

    - name: Stash unstaged changes
      run: git stash --include-untracked

    - name: Pull latest changes
      run: git pull --rebase origin main

    - name: Apply stashed changes (if any)
      run: git stash pop || true

    - name: Commit and push changes
      run: |
        git add logs/daily-updates.log
        git commit -m "Daily automated update $(date '+%Y-%m-%d')" || exit 0
        remote_repo="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vachan4471/daily_commit.git"
        git push "${remote_repo}" HEAD:main
